image: Visual Studio 2019
skip_commits:
  message: /doco|Merge pull request.*/
build_script:
- ps: >-
    dotnet build src --configuration Release

    dotnet test src --configuration Release --no-build --no-restore --filter Category!=Integration
after_build:
  - ps: Get-ChildItem .\**\*.received.* | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
test: off
artifacts:
  - path: '**\*.received.*'